# Generated by Django 6.0.1 on 2026-02-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(default='No cover letter provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted')], default='STATUS_SUBMITTED', max_length=20),
        ),
    ]
