# Generated by Django 6.0.1 on 2026-02-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_cover_letter_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted')], default='SUBMITTED', max_length=20),
        ),
    ]
